### ISSUE TITLE
Feature Request: re-sync with evanmiller mdbtools

### ISSUE THREAD

**Issue by Saijin-Naib** [lsgunth/mdbtools-win#2]
It looks like this fork (of a fork) has collected a ton of patches and has modernized the code a bit.

Would this project be interested in possibly re-syncing on this fork so that the Windows build could be updated?

**Comment by lsgunth** [comment]
I created this build for a purpose and shared it here because there was none available online.  I have no intention of updating it, but if you'd like to go right ahead.
