### ISSUE TITLE
Windows build instructions?

### ISSUE THREAD

**Issue by digitalcardboard** [lsgunth/mdbtools-win#4]
I've been struggling to try to get this to compile myself using MSYS2, do you have any suggestions for what I might be missing? The multiple environments are confusing to me, and at this point, I'm having issues with `locale_t`, which might come back to the compile environment, but of course, I'm not sure.

Any hints would be greatly appreciated!

**Comment by digitalcardboard** [comment]
I was finally able to get this sorted. :)

**Comment by lsgunth** [comment]
Oh, nice. Might be worth posting more of your issue and solution so other people can use it if they get stuck similarly.

**Comment by digitalcardboard** [comment]
> Oh, nice. Might be worth posting more of your issue and solution so other people can use it if they get stuck similarly.

Hopefully this became clearer as you found my breadcrumbs around the internet last weekend. Culmination is essentially here: https://github.com/lsgunth/mdbtools-win/blob/master/README.md
