### ISSUE TITLE
how to install binaries on Win10 to have ODBC drivers available?

### ISSUE THREAD

**Issue by abubelinha** [lsgunth/mdbtools-win#9]
@digitalcardboard @lsgunth could you give some instructions about how to use this to connect to a .mdb file through ODBC?
I mean so I can find it in the Windows 10 list of ODBC drivers. 
I need to connect a MS-Access .mdb file from a 64bit Python application, in a machine where the installed MS-Access version is 32bit.

[This pretty much describes my problem](https://stackoverflow.com/questions/45928987/is-it-possible-for-64-bit-pyodbc-to-talk-to-32-bit-ms-access-database). But [AccessDatabaseEngine executables](https://www.microsoft.com/en-us/download/details.aspx?id=13255) did not solve it (I tried both 32/64 bit versions ... but it looks like Python still gets confused and does not use the correct odbc driver).

So I am arriving here after reading this [stackoverflow answer](https://stackoverflow.com/questions/61805916/how-to-accommodate-both-32-bit-and-64-bit-odbc-drivers/61806252#61806252) where mdbtools was mentioned as an alternative.

But I don't know how to install it. I see very different .exe and .dll files, so this is not as simple as the single AccessDatabaseEngine installation executable. Which files should I use and where should I put them?

Also wondering ... "MDBTOOLS built for 32-bit Windows" means it is compatible with my old WinXP 32bit machine, but can I also run this on a Win10 64bit machine so it can communicate with a Python 64bit installation, or not?

**Comment by digitalcardboard** [comment]
I don't believe mdbtools provides an ODBC-style connection. I'm using it to just export tables from the MDB as a CSV. You're likely on the right track with pyodbc.

**Comment by abubelinha** [comment]
Thanks for your answer @digitalcardboard 
As far as I know, pyodbc uses installed odbc drivers to connect Access database. You mean I could connect in some other non-ODBC way?

As described in above links, there are troubles using MS-provided ODBC drivers from Python 64bit when your previously installed Office/Access version is 32bit (I can't change that, and I can't change Python to 32 because that would broke some other modules I use).

I ask about mdbtools-ODBC because there is an [entry about odbc in main mdbtools README](https://github.com/mdbtools/mdbtools#odbc), and I also found several [odbc-related issues](https://github.com/mdbtools/mdbtools/issues?q=is%3Aissue+odbc).

I might have misunderstood because I am not an expert in either Python or ODBC.

**Comment by digitalcardboard** [comment]
Ah, I see your point. These Windows binaries aren't built with ODBC support, as the library wasn't available in the build environment. I don't know what your project entails, but you might be able to use mdbtools to dump everything out to CSV or SQL and then use that in a different environment.

Apologies that I can't be of more help. I really only got the build working to use `mdb-export`.

**Comment by abubelinha** [comment]
Ah ok.  Now I understand.
I thought this was a full Windows port of mdbtools.
Thanks a lot for clarifying. I suggest you to explain this in the main page, so people does not get confused.
